"""MangaOwned table

Revision ID: 85f8de81f405
Revises: 25b2ec8a4bf0
Create Date: 2018-11-25 02:14:05.467148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85f8de81f405'
down_revision = '25b2ec8a4bf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manga_owned',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=True),
    sa.Column('author', sa.String(length=140), nullable=True),
    sa.Column('volume_owned', sa.String(length=140), nullable=True),
    sa.Column('volume_available', sa.String(length=140), nullable=True),
    sa.Column('finished_series', sa.String(length=140), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manga_owned_title'), 'manga_owned', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_manga_owned_title'), table_name='manga_owned')
    op.drop_table('manga_owned')
    # ### end Alembic commands ###
